/*
 * MainDialog.java
 *
 * Created on 5 June 2008, 12:54
 */

/**
 *
 * @author V.Kravtsov
 */
import jpos.*;
import java.io.*;
import javax.swing.*;
import jpos.FiscalPrinter;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

import com.shtrih.cashdrawer.*;
import com.shtrih.fiscalprinter.*;
import com.shtrih.jpos.fiscalprinter.*;
import com.shtrih.fiscalprinter.command.*;
import jpos.events.ErrorEvent;
import jpos.events.ErrorListener;
import jpos.events.DirectIOEvent;
import jpos.events.DirectIOListener;
import jpos.events.StatusUpdateEvent;
import jpos.events.StatusUpdateListener;

public class MainDialog extends javax.swing.JDialog
        implements DirectIOListener, StatusUpdateListener, ErrorListener {

    private static String encoding = "";
    ShtrihCashDrawer cashDrawer = new ShtrihCashDrawer(encoding);
    ShtrihFiscalPrinter printer = new ShtrihFiscalPrinter(encoding);
    PrinterTest controller = new PrinterTest(printer);
    DefaultListModel eventList = new DefaultListModel();

    /**
     * Creates new form MainDialog
     */
    public MainDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        printer.addDirectIOListener(this);
        printer.addStatusUpdateListener(this);
        printer.addErrorListener(this);
        lbEvents.setModel(eventList);
        System.out.println(System.getProperty("os.name"));
    System.out.println(System.getProperty("os.arch"));
    System.out.println(System.getProperty("os.version"));
    }

    public String getEventTimeStamp() {
        DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss ");
        return dateFormat.format(new Date());
    }

    public void statusUpdateOccurred(StatusUpdateEvent e) {
        String text = getEventTimeStamp() + "StatusUpdateEvent(Status: "
                + com.shtrih.jpos.StatusUpdateEventHelper.getName(e.getStatus()) + ")";

        eventList.addElement(text);
    }

    public void errorOccurred(ErrorEvent e) {
        String text = getEventTimeStamp() + "ErrorEvent("
                + "ErrorCode: " + e.getErrorCode() + ", "
                + "ErrorCodeExtended: " + e.getErrorCodeExtended() + ", "
                + "ErrorLocus: " + e.getErrorLocus() + ", "
                + "ErrorResponse: " + e.getErrorResponse() + ")";
        eventList.addElement(text);
    }

    public void directIOOccurred(DirectIOEvent e) {
        String text = getEventTimeStamp() + "DirectIOEvent(EventNumber: " + e.getEventNumber() + ", "
                + "Data: " + e.getData() + ")";
        eventList.addElement(text);
    }

    private void updateDayOpened() {
        try {
            if (printer.getDayOpened()) {
                edtDayOpened.setText("Day is opened");
            } else {
                edtDayOpened.setText("Day is not opened");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane1 = new javax.swing.JTabbedPane();
        pnlFptr1 = new javax.swing.JPanel();
        btnPrintNonfiscalReceipt = new javax.swing.JButton();
        btnPrintFiscalReceipt = new javax.swing.JButton();
        btnSetHeaderLines = new javax.swing.JButton();
        btnSetTrailerLines = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        edtDeviceName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPrintCashIn = new javax.swing.JButton();
        btnPrintCashOut = new javax.swing.JButton();
        btnPrintRefundReceipt = new javax.swing.JButton();
        btnZReport = new javax.swing.JButton();
        btnZReport1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnClaim = new javax.swing.JButton();
        btnRelease = new javax.swing.JButton();
        btnEnable = new javax.swing.JButton();
        btnDisable = new javax.swing.JButton();
        btnResetPrinter = new javax.swing.JButton();
        lblDayOpened = new javax.swing.JLabel();
        edtDayOpened = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblDayOpened1 = new javax.swing.JLabel();
        lblDayOpened2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnXReport = new javax.swing.JButton();
        btnPrintDuplicateReceipt = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        lblDayOpened3 = new javax.swing.JLabel();
        btnESCBarcodesPrintNormal = new javax.swing.JButton();
        btnESCBarcodesPrintRecMessage = new javax.swing.JButton();
        btnPrintFiscalReceipt2 = new javax.swing.JButton();
        btnOpenDay = new javax.swing.JButton();
        btnPrintFiscalReceipt3 = new javax.swing.JButton();
        btnPrintBarcodes = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        lblBarcode = new javax.swing.JLabel();
        btnExecuteCommand = new javax.swing.JButton();
        btnEnable1 = new javax.swing.JButton();
        btnDisable1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlFptr2 = new javax.swing.JPanel();
        btnReadStatus = new javax.swing.JButton();
        Pane2 = new javax.swing.JScrollPane();
        Memo1 = new javax.swing.JEditorPane();
        btnReadCashReg = new javax.swing.JButton();
        btnReadOperReg = new javax.swing.JButton();
        btnGetData = new javax.swing.JButton();
        btnReadMaxGraphics = new javax.swing.JButton();
        btnGetGrandTotal = new javax.swing.JButton();
        btnPrintSpeedTest = new javax.swing.JButton();
        pnlImage = new javax.swing.JPanel();
        pnlReceiptImage = new javax.swing.JPanel();
        edtImageFile = new javax.swing.JTextField();
        lblImageFile = new javax.swing.JLabel();
        btnLoadImages = new javax.swing.JButton();
        btnPrintImage = new javax.swing.JButton();
        btnClearImages = new javax.swing.JButton();
        lblImageIndex = new javax.swing.JLabel();
        seImageIndex = new javax.swing.JSpinner();
        btnClearLogos = new javax.swing.JButton();
        btnLoadImage = new javax.swing.JButton();
        lblLogoPosition = new javax.swing.JLabel();
        cbLogoPosition = new javax.swing.JComboBox();
        btnAddLogo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbllineHeight = new javax.swing.JLabel();
        seLineHeight = new javax.swing.JSpinner();
        lblLineType = new javax.swing.JLabel();
        cbLineType = new javax.swing.JComboBox();
        btnPrintLine = new javax.swing.JButton();
        btnLoadLogo = new javax.swing.JButton();
        btnPrintReceiptLogo = new javax.swing.JButton();
        btnAdidasReceiptTest = new javax.swing.JButton();
        btnAdidasReceiptTest1 = new javax.swing.JButton();
        BarcodePanel = new javax.swing.JPanel();
        btnClearEvents = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbEvents = new javax.swing.JList();
        pnlCash1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edtCashDrawerDeviceName = new javax.swing.JTextField();
        edtCashDrawerTimeout = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chbCashDrawerDeviceEnabled = new javax.swing.JCheckBox();
        chbCashDrawerFreezeEvents = new javax.swing.JCheckBox();
        edtCashDrawerBeepTimeout = new javax.swing.JTextField();
        edtCashDrawerBeepDelay = new javax.swing.JTextField();
        edtCashDrawerBeepDuration = new javax.swing.JTextField();
        edtCashDrawerBeepFrequency = new javax.swing.JTextField();
        btnCashDrawerOpenDrawer = new javax.swing.JButton();
        btnCashDrawerClaim = new javax.swing.JButton();
        btnCashDrawerOpen = new javax.swing.JButton();
        btnCashDrawerClose = new javax.swing.JButton();
        btnCashDrawerRelease = new javax.swing.JButton();
        btnCashDrawerWaitForDrawerClose = new javax.swing.JButton();
        btnCashDrawerGetState = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReport = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFptr1.setFocusable(false);
        pnlFptr1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrintNonfiscalReceipt.setText("non fiscal receipt");
        btnPrintNonfiscalReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintNonfiscalReceiptActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnPrintNonfiscalReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 160, 26));

        btnPrintFiscalReceipt.setText("fiscal receipt");
        btnPrintFiscalReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintFiscalReceiptActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnPrintFiscalReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 206, 160, 30));

        btnSetHeaderLines.setText("setHeaderLines");
        btnSetHeaderLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetHeaderLinesActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnSetHeaderLines, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 160, 26));

        btnSetTrailerLines.setText("setTrailerLines");
        btnSetTrailerLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetTrailerLinesActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnSetTrailerLines, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 160, 26));

        jButton5.setText("open");
        jButton5.setHideActionText(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnlFptr1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 160, 26));

        jButton6.setText("close");
        jButton6.setHideActionText(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pnlFptr1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 160, 26));

        edtDeviceName.setText("ShtrihFptr");
        edtDeviceName.setName("edtDeviceName"); // NOI18N
        pnlFptr1.add(edtDeviceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 200, -1));

        jLabel1.setText("Device name:");
        pnlFptr1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        btnPrintCashIn.setText("print cash in");
        btnPrintCashIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintCashInActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnPrintCashIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 160, 26));

        btnPrintCashOut.setText("print cash out");
        btnPrintCashOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintCashOutActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnPrintCashOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, 26));

        btnPrintRefundReceipt.setText("refund receipt");
        btnPrintRefundReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintRefundReceiptActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnPrintRefundReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 160, 26));

        btnZReport.setText("Z Report");
        btnZReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZReportActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnZReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 160, 26));

        btnZReport1.setText("Z Report");
        btnZReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZReport1ActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnZReport1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 25));
        pnlFptr1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 570, 10));

        btnClaim.setText("claim");
        btnClaim.setHideActionText(true);
        btnClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaimActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnClaim, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 160, 26));

        btnRelease.setText("release");
        btnRelease.setHideActionText(true);
        btnRelease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReleaseActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnRelease, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 160, 26));

        btnEnable.setText("enable");
        btnEnable.setHideActionText(true);
        btnEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnEnable, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 160, 26));

        btnDisable.setText("disable");
        btnDisable.setHideActionText(true);
        btnDisable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisableActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnDisable, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 160, 26));

        btnResetPrinter.setText("resetPrinter");
        btnResetPrinter.setHideActionText(true);
        btnResetPrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPrinterActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnResetPrinter, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 160, 26));

        lblDayOpened.setText("Receipts");
        pnlFptr1.add(lblDayOpened, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, -1));

        edtDayOpened.setBackground(new java.awt.Color(204, 204, 204));
        edtDayOpened.setName("edtFileName"); // NOI18N
        pnlFptr1.add(edtDayOpened, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 200, -1));
        pnlFptr1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 630, 10));

        lblDayOpened1.setText("Day opened:");
        pnlFptr1.add(lblDayOpened1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        lblDayOpened2.setText("Reports");
        pnlFptr1.add(lblDayOpened2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 60, -1));
        pnlFptr1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 570, 10));

        btnXReport.setText("X Report");
        btnXReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXReportActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnXReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 160, 26));

        btnPrintDuplicateReceipt.setText("duplicate receipt");
        btnPrintDuplicateReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintDuplicateReceiptActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnPrintDuplicateReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 160, 26));
        pnlFptr1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 570, 10));

        lblDayOpened3.setText("ESC");
        pnlFptr1.add(lblDayOpened3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 60, -1));

        btnESCBarcodesPrintNormal.setText("ESC barcodes via PrintNormal");
        btnESCBarcodesPrintNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnESCBarcodesPrintNormalActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnESCBarcodesPrintNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 290, 26));

        btnESCBarcodesPrintRecMessage.setText("ESC barcodes via PrintRecMessage");
        btnESCBarcodesPrintRecMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnESCBarcodesPrintRecMessageActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnESCBarcodesPrintRecMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 290, 26));

        btnPrintFiscalReceipt2.setText("voided receipt");
        btnPrintFiscalReceipt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintFiscalReceipt2ActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnPrintFiscalReceipt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 160, 26));

        btnOpenDay.setText("Open day");
        btnOpenDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDayActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnOpenDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 160, 26));

        btnPrintFiscalReceipt3.setText("fiscal receipt 3");
        btnPrintFiscalReceipt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintFiscalReceipt3ActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnPrintFiscalReceipt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 160, 30));

        btnPrintBarcodes.setText("Print barcodes");
        btnPrintBarcodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintBarcodesActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnPrintBarcodes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 160, 26));
        pnlFptr1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 570, 10));

        lblBarcode.setText("Barcode");
        pnlFptr1.add(lblBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 60, -1));

        btnExecuteCommand.setText("Execute command");
        btnExecuteCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteCommandActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnExecuteCommand, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 200, 30));

        btnEnable1.setText("enablePowerNotify");
        btnEnable1.setHideActionText(true);
        btnEnable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnable1ActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnEnable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 160, 26));

        btnDisable1.setText("disablePowerNotify");
        btnDisable1.setHideActionText(true);
        btnDisable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisable1ActionPerformed(evt);
            }
        });
        pnlFptr1.add(btnDisable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 160, 26));

        jButton1.setText("FSDiscountTest");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlFptr1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 160, -1));

        tabPane1.addTab("FiscalPrinter", pnlFptr1);

        pnlFptr2.setFocusCycleRoot(true);
        pnlFptr2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReadStatus.setText("readStatus");
        btnReadStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadStatusActionPerformed(evt);
            }
        });
        pnlFptr2.add(btnReadStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 10, 130, -1));

        Memo1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        Memo1.setPreferredSize(new java.awt.Dimension(10, 23));
        Pane2.setViewportView(Memo1);

        pnlFptr2.add(Pane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 460));

        btnReadCashReg.setText("read cash registers");
        btnReadCashReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadCashRegActionPerformed(evt);
            }
        });
        pnlFptr2.add(btnReadCashReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        btnReadOperReg.setText("operation registers");
        btnReadOperReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadOperRegActionPerformed(evt);
            }
        });
        pnlFptr2.add(btnReadOperReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 130, -1));

        btnGetData.setText("getDailyTotal");
        btnGetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDataActionPerformed(evt);
            }
        });
        pnlFptr2.add(btnGetData, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 130, -1));

        btnReadMaxGraphics.setText("read max graphics");
        btnReadMaxGraphics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadMaxGraphicsActionPerformed(evt);
            }
        });
        pnlFptr2.add(btnReadMaxGraphics, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 130, -1));

        btnGetGrandTotal.setText("getGrandTotal");
        btnGetGrandTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetGrandTotalActionPerformed(evt);
            }
        });
        pnlFptr2.add(btnGetGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 130, -1));

        btnPrintSpeedTest.setText("Print speed test");
        btnPrintSpeedTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintSpeedTestActionPerformed(evt);
            }
        });
        pnlFptr2.add(btnPrintSpeedTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 130, -1));

        tabPane1.addTab("Printer status", pnlFptr2);

        pnlImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlReceiptImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Receipt image"));
        pnlReceiptImage.setName(""); // NOI18N
        pnlReceiptImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtImageFile.setText("Logo2.bmp");
        edtImageFile.setName("edtFileName"); // NOI18N
        pnlReceiptImage.add(edtImageFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 180, -1));

        lblImageFile.setText("Image file:");
        pnlReceiptImage.add(lblImageFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 65, -1));

        btnLoadImages.setText("Load images");
        btnLoadImages.setName("btnLoadImages"); // NOI18N
        btnLoadImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadImagesActionPerformed(evt);
            }
        });
        pnlReceiptImage.add(btnLoadImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 110, 26));

        btnPrintImage.setText("Print image");
        btnPrintImage.setName("btnPrintImages"); // NOI18N
        btnPrintImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintImageActionPerformed(evt);
            }
        });
        pnlReceiptImage.add(btnPrintImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 110, 26));

        btnClearImages.setText("Clear images");
        btnClearImages.setName("btnLoadImages"); // NOI18N
        btnClearImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearImagesActionPerformed(evt);
            }
        });
        pnlReceiptImage.add(btnClearImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 110, 26));

        lblImageIndex.setText("Image index:");
        pnlReceiptImage.add(lblImageIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 65, -1));
        pnlReceiptImage.add(seImageIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 180, 20));

        btnClearLogos.setText("Clear logos");
        btnClearLogos.setName("btnClearReceiptLogo"); // NOI18N
        btnClearLogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLogosActionPerformed(evt);
            }
        });
        pnlReceiptImage.add(btnClearLogos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 110, 26));

        btnLoadImage.setText("Load image");
        btnLoadImage.setName("btnLoadImages"); // NOI18N
        btnLoadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadImageActionPerformed(evt);
            }
        });
        pnlReceiptImage.add(btnLoadImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 110, 26));

        lblLogoPosition.setText("Logo position:");
        pnlReceiptImage.add(lblLogoPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, -1));

        cbLogoPosition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlReceiptImage.add(cbLogoPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 170, -1));

        btnAddLogo.setText("Add logo");
        btnAddLogo.setName("btnSetReceiptLogo"); // NOI18N
        btnAddLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLogoActionPerformed(evt);
            }
        });
        pnlReceiptImage.add(btnAddLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 110, 26));

        pnlImage.add(pnlReceiptImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 230));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Graphics line"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllineHeight.setText("Line height:");
        jPanel1.add(lbllineHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 65, -1));

        seLineHeight.setValue(100);
        jPanel1.add(seLineHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 130, 20));

        lblLineType.setText("Line type:");
        jPanel1.add(lblLineType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, -1));

        cbLineType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbLineType, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 130, -1));

        btnPrintLine.setText("Print line");
        btnPrintLine.setName("btnSetReceiptLogo"); // NOI18N
        btnPrintLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintLineActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrintLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 110, 26));

        pnlImage.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 410, 110));

        btnLoadLogo.setText("Load logos");
        btnLoadLogo.setName("btnSetReceiptLogo"); // NOI18N
        btnLoadLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadLogoActionPerformed(evt);
            }
        });
        pnlImage.add(btnLoadLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 170, 40));

        btnPrintReceiptLogo.setText("Print receipt with logo");
        btnPrintReceiptLogo.setName("btnSetReceiptLogo"); // NOI18N
        btnPrintReceiptLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReceiptLogoActionPerformed(evt);
            }
        });
        pnlImage.add(btnPrintReceiptLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 170, 40));

        btnAdidasReceiptTest.setText("Adidas receipt - print");
        btnAdidasReceiptTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdidasReceiptTestActionPerformed(evt);
            }
        });
        pnlImage.add(btnAdidasReceiptTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 200, 30));

        btnAdidasReceiptTest1.setText("Adidas receipt - load images");
        btnAdidasReceiptTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdidasReceiptTest1ActionPerformed(evt);
            }
        });
        pnlImage.add(btnAdidasReceiptTest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, 30));

        tabPane1.addTab("Image", pnlImage);

        BarcodePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClearEvents.setText("Clear");
        btnClearEvents.setHideActionText(true);
        btnClearEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearEventsActionPerformed(evt);
            }
        });
        BarcodePanel.add(btnClearEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 90, 26));

        jScrollPane2.setViewportView(lbEvents);

        BarcodePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 430));

        tabPane1.addTab("Events", BarcodePanel);

        pnlCash1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Device name:");
        pnlCash1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setText("Timeout:");
        pnlCash1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        edtCashDrawerDeviceName.setText("ShtrihCashDrawer");
        edtCashDrawerDeviceName.setName("edtDeviceName"); // NOI18N
        pnlCash1.add(edtCashDrawerDeviceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 213, -1));

        edtCashDrawerTimeout.setText("1000");
        edtCashDrawerTimeout.setName("edtDeviceName"); // NOI18N
        pnlCash1.add(edtCashDrawerTimeout, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 213, -1));

        jLabel9.setText("beepFrequency:");
        pnlCash1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel10.setText("beepDuration:");
        pnlCash1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel11.setText("beepDelay:");
        pnlCash1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel8.setText("beepTimeout:");
        pnlCash1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        chbCashDrawerDeviceEnabled.setText("DeviceEnabled");
        chbCashDrawerDeviceEnabled.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chbCashDrawerDeviceEnabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCashDrawerDeviceEnabledActionPerformed(evt);
            }
        });
        pnlCash1.add(chbCashDrawerDeviceEnabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        chbCashDrawerFreezeEvents.setText("FreezeEvents");
        chbCashDrawerFreezeEvents.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chbCashDrawerFreezeEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCashDrawerFreezeEventsActionPerformed(evt);
            }
        });
        pnlCash1.add(chbCashDrawerFreezeEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 99, -1));

        edtCashDrawerBeepTimeout.setText("1000");
        edtCashDrawerBeepTimeout.setName("edtDeviceName"); // NOI18N
        pnlCash1.add(edtCashDrawerBeepTimeout, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 100, 200, -1));

        edtCashDrawerBeepDelay.setText("200");
        edtCashDrawerBeepDelay.setName("edtDeviceName"); // NOI18N
        pnlCash1.add(edtCashDrawerBeepDelay, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 190, 200, -1));

        edtCashDrawerBeepDuration.setText("10000");
        edtCashDrawerBeepDuration.setName("edtDeviceName"); // NOI18N
        pnlCash1.add(edtCashDrawerBeepDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 160, 200, -1));

        edtCashDrawerBeepFrequency.setText("2000");
        edtCashDrawerBeepFrequency.setName("edtDeviceName"); // NOI18N
        pnlCash1.add(edtCashDrawerBeepFrequency, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 130, 200, -1));

        btnCashDrawerOpenDrawer.setText("openDrawer");
        btnCashDrawerOpenDrawer.setHideActionText(true);
        btnCashDrawerOpenDrawer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashDrawerOpenDrawerActionPerformed(evt);
            }
        });
        pnlCash1.add(btnCashDrawerOpenDrawer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 117, 26));

        btnCashDrawerClaim.setText("claim");
        btnCashDrawerClaim.setHideActionText(true);
        btnCashDrawerClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashDrawerClaimActionPerformed(evt);
            }
        });
        pnlCash1.add(btnCashDrawerClaim, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 117, 26));

        btnCashDrawerOpen.setText("open");
        btnCashDrawerOpen.setHideActionText(true);
        btnCashDrawerOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashDrawerOpenActionPerformed(evt);
            }
        });
        pnlCash1.add(btnCashDrawerOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 117, 26));

        btnCashDrawerClose.setText("close");
        btnCashDrawerClose.setHideActionText(true);
        btnCashDrawerClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashDrawerCloseActionPerformed(evt);
            }
        });
        pnlCash1.add(btnCashDrawerClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 104, 26));

        btnCashDrawerRelease.setText("release");
        btnCashDrawerRelease.setHideActionText(true);
        btnCashDrawerRelease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashDrawerReleaseActionPerformed(evt);
            }
        });
        pnlCash1.add(btnCashDrawerRelease, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 104, 26));

        btnCashDrawerWaitForDrawerClose.setText("waitForDrawerClose");
        btnCashDrawerWaitForDrawerClose.setHideActionText(true);
        btnCashDrawerWaitForDrawerClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashDrawerWaitForDrawerCloseActionPerformed(evt);
            }
        });
        pnlCash1.add(btnCashDrawerWaitForDrawerClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 227, 26));

        btnCashDrawerGetState.setText("getDrawerState");
        btnCashDrawerGetState.setHideActionText(true);
        btnCashDrawerGetState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashDrawerGetStateActionPerformed(evt);
            }
        });
        pnlCash1.add(btnCashDrawerGetState, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 227, 26));

        txtReport.setColumns(20);
        txtReport.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtReport.setRows(5);
        jScrollPane1.setViewportView(txtReport);

        pnlCash1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 229, 530, 220));

        tabPane1.addTab("CashDrawer", pnlCash1);

        getContentPane().add(tabPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 510));

        btnClose.setText("close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 90, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearImagesActionPerformed
        try {
            printer.clearImages();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnClearImagesActionPerformed

    private void btnReadOperRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadOperRegActionPerformed
        Memo1.setText(controller.readOperRegisters());
    }//GEN-LAST:event_btnReadOperRegActionPerformed

    private void btnReadCashRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadCashRegActionPerformed
        Memo1.setText(controller.readCashRegisters());
    }//GEN-LAST:event_btnReadCashRegActionPerformed

    private void btnReadStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadStatusActionPerformed
        Memo1.setText(controller.readStatus());
    }//GEN-LAST:event_btnReadStatusActionPerformed

    private void btnPrintLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintLineActionPerformed
        try {
            int lineHeight = (Integer) seLineHeight.getValue();
            int lineType = cbLineType.getSelectedIndex();
            printer.printLine(lineType, lineHeight);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintLineActionPerformed

    private void btnClearLogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLogosActionPerformed
        try {
            printer.clearLogo();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnClearLogosActionPerformed

    private void btnLoadImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadImagesActionPerformed
        controller.loadImages();
    }//GEN-LAST:event_btnLoadImagesActionPerformed

    private void btnPrintImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintImageActionPerformed
        try {
            printer.printImage((Integer) seImageIndex.getValue());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintImageActionPerformed

    private void btnZReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZReport1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_btnZReport1ActionPerformed

    private void btnZReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZReportActionPerformed
        controller.printZReport();
    }//GEN-LAST:event_btnZReportActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCashDrawerGetStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashDrawerGetStateActionPerformed
        try {
            if (cashDrawer.getDrawerOpened()) {
                txtReport.setText("Drawer is opened");
            } else {
                txtReport.setText("Drawer is closed");
            }
        } catch (JposException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCashDrawerGetStateActionPerformed

    private void btnCashDrawerWaitForDrawerCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashDrawerWaitForDrawerCloseActionPerformed
        try {
            cashDrawer.waitForDrawerClose(
                    Integer.parseInt(edtCashDrawerBeepTimeout.getText()),
                    Integer.parseInt(edtCashDrawerBeepFrequency.getText()),
                    Integer.parseInt(edtCashDrawerBeepDuration.getText()),
                    Integer.parseInt(edtCashDrawerBeepDelay.getText()));
        } catch (JposException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCashDrawerWaitForDrawerCloseActionPerformed

    private void btnCashDrawerReleaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashDrawerReleaseActionPerformed
        try {
            cashDrawer.release();
        } catch (JposException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCashDrawerReleaseActionPerformed

    private void btnCashDrawerCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashDrawerCloseActionPerformed
        try {
            cashDrawer.close();
        } catch (JposException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCashDrawerCloseActionPerformed

    private void btnCashDrawerOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashDrawerOpenActionPerformed
        try {
            cashDrawer.open(edtCashDrawerDeviceName.getText());
            if (cashDrawer.getCapStatus()) {
                txtReport.setText("CapStatus = true");
            } else {
                txtReport.setText("CapStatus = false");
            }
        } catch (JposException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCashDrawerOpenActionPerformed

    private void btnCashDrawerClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashDrawerClaimActionPerformed
        try {
            cashDrawer.claim(Integer.parseInt(edtCashDrawerTimeout.getText()));
        } catch (JposException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCashDrawerClaimActionPerformed

    private void btnCashDrawerOpenDrawerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashDrawerOpenDrawerActionPerformed
        try {
            cashDrawer.openDrawer();
        } catch (JposException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCashDrawerOpenDrawerActionPerformed

    private void chbCashDrawerFreezeEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCashDrawerFreezeEventsActionPerformed
        try {
            cashDrawer.setFreezeEvents(
                    chbCashDrawerFreezeEvents.getModel().isSelected());
        } catch (JposException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_chbCashDrawerFreezeEventsActionPerformed

    private void chbCashDrawerDeviceEnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCashDrawerDeviceEnabledActionPerformed
        try {
            cashDrawer.setDeviceEnabled(chbCashDrawerDeviceEnabled.getModel().isSelected());
        } catch (JposException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_chbCashDrawerDeviceEnabledActionPerformed

    private void btnPrintRefundReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintRefundReceiptActionPerformed
        controller.printRefundReceipt();
    }//GEN-LAST:event_btnPrintRefundReceiptActionPerformed

    private void btnPrintCashOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintCashOutActionPerformed
        controller.printCashOutReceipt();
    }//GEN-LAST:event_btnPrintCashOutActionPerformed

    private void btnPrintCashInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintCashInActionPerformed
        controller.printCashInReceipt();
    }//GEN-LAST:event_btnPrintCashInActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        controller.close();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        controller.open(edtDeviceName.getText());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnSetTrailerLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetTrailerLinesActionPerformed
        controller.setTrailerLines();
    }//GEN-LAST:event_btnSetTrailerLinesActionPerformed

    private void btnSetHeaderLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetHeaderLinesActionPerformed
        controller.setHeaderLines();
    }//GEN-LAST:event_btnSetHeaderLinesActionPerformed

    private void btnPrintFiscalReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintFiscalReceiptActionPerformed
        controller.printFiscalReceipt();
    }//GEN-LAST:event_btnPrintFiscalReceiptActionPerformed

    private void btnPrintNonfiscalReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintNonfiscalReceiptActionPerformed
        controller.printNonFiscal(true);
    }//GEN-LAST:event_btnPrintNonfiscalReceiptActionPerformed

    private void btnGetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDataActionPerformed
        Memo1.setText(controller.getDailyTotal());
    }//GEN-LAST:event_btnGetDataActionPerformed

    private void btnClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaimActionPerformed
        controller.claim();
    }//GEN-LAST:event_btnClaimActionPerformed

    private void btnReleaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReleaseActionPerformed
        controller.release();
    }//GEN-LAST:event_btnReleaseActionPerformed

    private void btnLoadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadImageActionPerformed
        try {
            int index = printer.loadImage(edtImageFile.getText());
            seImageIndex.setValue(index);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLoadImageActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String[] LogoPositions = {
            "After header",
            "Before trailer",
            "After trailer",
            "After additional trailer",
            "Before header"
        };
        DefaultComboBoxModel model = new DefaultComboBoxModel(LogoPositions);
        cbLogoPosition.setModel(model);

        String[] LineTypes = {
            "Solid",
            "White"};
        model = new DefaultComboBoxModel(LineTypes);
        cbLineType.setModel(model);
    }//GEN-LAST:event_formWindowOpened

    private void btnAddLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLogoActionPerformed
        try {
            int imageIndex = (Integer) seImageIndex.getValue();
            int logoPosition = cbLogoPosition.getSelectedIndex();
            printer.addLogo(imageIndex, logoPosition);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddLogoActionPerformed

    private void btnLoadLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadLogoActionPerformed
        try {
            /////////////////////////////////////////////////////////////////
            // Logo initialization
            // This can be done once per day.
            // Image information stored in xml file.

            printer.clearLogo();
            printer.clearImages();
            printer.loadImage("Logo0.bmp"); // 0
            printer.loadImage("Logo1.bmp"); // 1
            printer.loadImage("Logo2.bmp"); // 2
            printer.loadImage("Logo3.bmp"); // 3
            printer.loadImage("Logo4.bmp"); // 4
            printer.addLogo(0, SmFptrConst.SMFPTR_LOGO_BEFORE_HEADER);
            printer.addLogo(1, SmFptrConst.SMFPTR_LOGO_AFTER_HEADER);
            printer.addLogo(2, SmFptrConst.SMFPTR_LOGO_BEFORE_TRAILER);
            printer.addLogo(3, SmFptrConst.SMFPTR_LOGO_AFTER_TRAILER);
            printer.addLogo(4, SmFptrConst.SMFPTR_LOGO_AFTER_ADDTRAILER);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnLoadLogoActionPerformed

    private void btnReadMaxGraphicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadMaxGraphicsActionPerformed
        Memo1.setText(controller.readMaxGraphics());
    }//GEN-LAST:event_btnReadMaxGraphicsActionPerformed

    private void btnPrintReceiptLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReceiptLogoActionPerformed
        try {
            // Nonfiscal receipt
            printer.beginNonFiscal();
            printer.printNormal(FiscalPrinterConst.FPTR_S_RECEIPT, "Nonfiscal receipt, line 1");
            printer.printNormal(FiscalPrinterConst.FPTR_S_RECEIPT, "Nonfiscal receipt, line 2");
            printer.printNormal(FiscalPrinterConst.FPTR_S_RECEIPT, "Nonfiscal receipt, line 3");
            printer.endNonFiscal();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintReceiptLogoActionPerformed

    private void btnAdidasReceiptTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdidasReceiptTestActionPerformed
        //AdidasReceiptTest test = new AdidasReceiptTest(printer);
        //test.printReceipt();
    }//GEN-LAST:event_btnAdidasReceiptTestActionPerformed

    private void btnAdidasReceiptTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdidasReceiptTest1ActionPerformed
        //AdidasReceiptTest test = new AdidasReceiptTest(printer);
        //test.loadImages();
    }//GEN-LAST:event_btnAdidasReceiptTest1ActionPerformed

    private void btnGetGrandTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetGrandTotalActionPerformed
        Memo1.setText(controller.getGrandTotal());
    }//GEN-LAST:event_btnGetGrandTotalActionPerformed

    private void btnClearEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearEventsActionPerformed
        eventList.clear();
    }//GEN-LAST:event_btnClearEventsActionPerformed

    private void btnEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableActionPerformed
        controller.enableDevice();
        updateDayOpened();
    }//GEN-LAST:event_btnEnableActionPerformed

    private void btnDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisableActionPerformed
        controller.disableDevice();
    }//GEN-LAST:event_btnDisableActionPerformed

    private void btnResetPrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPrinterActionPerformed
        controller.resetPrinter();
    }//GEN-LAST:event_btnResetPrinterActionPerformed

    private void btnXReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXReportActionPerformed
        controller.printXReport();
    }//GEN-LAST:event_btnXReportActionPerformed

    private void btnPrintDuplicateReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintDuplicateReceiptActionPerformed
        controller.printDuplicateReceipt();
    }//GEN-LAST:event_btnPrintDuplicateReceiptActionPerformed

    private void btnESCBarcodesPrintNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnESCBarcodesPrintNormalActionPerformed
        controller.printEscBarcodesNormal();
    }//GEN-LAST:event_btnESCBarcodesPrintNormalActionPerformed

    private void btnESCBarcodesPrintRecMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnESCBarcodesPrintRecMessageActionPerformed
        controller.printEscBarcodesRecMessage();
    }//GEN-LAST:event_btnESCBarcodesPrintRecMessageActionPerformed

    private void btnPrintFiscalReceipt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintFiscalReceipt2ActionPerformed
        controller.printCancelledReceipt();
    }//GEN-LAST:event_btnPrintFiscalReceipt2ActionPerformed

    private void btnPrintSpeedTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintSpeedTestActionPerformed
        Memo1.setText("");
        long time = System.currentTimeMillis();
        controller.printSpeedTest2();
        time = System.currentTimeMillis() - time;
        Memo1.setText("Print time: " + time + " ms.");

    }//GEN-LAST:event_btnPrintSpeedTestActionPerformed

    private void btnOpenDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDayActionPerformed
        try {
            printer.executeCommand(0xE0, 1000, "30");
        } catch (Exception e) {
            System.out.println("ERROR: " + e);
        }
    }//GEN-LAST:event_btnOpenDayActionPerformed

    private void btnPrintFiscalReceipt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintFiscalReceipt3ActionPerformed
        controller.printFiscalReceipt3();
    }//GEN-LAST:event_btnPrintFiscalReceipt3ActionPerformed

    private void btnPrintBarcodesActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        try {
            controller.printBarcodes();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }                                                

    private void btnPrintEJournalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintBarcodesActionPerformed
        try {
            controller.printJournalDocRange(427, 429);
            //controller.printJournalDocRange(1,1000);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintBarcodesActionPerformed

    private void btnExecuteCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteCommandActionPerformed
        controller.executeCommand();
    }//GEN-LAST:event_btnExecuteCommandActionPerformed

    private void btnEnable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnable1ActionPerformed
        try {
            printer.setPowerNotify(JposConst.JPOS_PN_ENABLED);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEnable1ActionPerformed

    private void btnDisable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisable1ActionPerformed
        try {
            printer.setPowerNotify(JposConst.JPOS_PN_DISABLED);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDisable1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            controller.printFSDiscountTestReceipt();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Установка вывода консольных сообщений в нужной кодировке
        try {
            System.setOut(new CodepagePrintStream(
                    System.out, System.getProperty("console.encoding", "Cp866")));
        } catch (UnsupportedEncodingException e) {
            System.out.println("Unable to setup console codepage: " + e);
        }

        setSystemLookAndFeel();
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    public static void setSystemLookAndFeel() {
        try {
            // Set System L&F
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarcodePanel;
    private javax.swing.JEditorPane Memo1;
    private javax.swing.JScrollPane Pane2;
    private javax.swing.JButton btnAddLogo;
    private javax.swing.JButton btnAdidasReceiptTest;
    private javax.swing.JButton btnAdidasReceiptTest1;
    private javax.swing.JButton btnCashDrawerClaim;
    private javax.swing.JButton btnCashDrawerClose;
    private javax.swing.JButton btnCashDrawerGetState;
    private javax.swing.JButton btnCashDrawerOpen;
    private javax.swing.JButton btnCashDrawerOpenDrawer;
    private javax.swing.JButton btnCashDrawerRelease;
    private javax.swing.JButton btnCashDrawerWaitForDrawerClose;
    private javax.swing.JButton btnClaim;
    private javax.swing.JButton btnClearEvents;
    private javax.swing.JButton btnClearImages;
    private javax.swing.JButton btnClearLogos;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDisable;
    private javax.swing.JButton btnDisable1;
    private javax.swing.JButton btnESCBarcodesPrintNormal;
    private javax.swing.JButton btnESCBarcodesPrintRecMessage;
    private javax.swing.JButton btnEnable;
    private javax.swing.JButton btnEnable1;
    private javax.swing.JButton btnExecuteCommand;
    private javax.swing.JButton btnGetData;
    private javax.swing.JButton btnGetGrandTotal;
    private javax.swing.JButton btnLoadImage;
    private javax.swing.JButton btnLoadImages;
    private javax.swing.JButton btnLoadLogo;
    private javax.swing.JButton btnOpenDay;
    private javax.swing.JButton btnPrintBarcodes;
    private javax.swing.JButton btnPrintCashIn;
    private javax.swing.JButton btnPrintCashOut;
    private javax.swing.JButton btnPrintDuplicateReceipt;
    private javax.swing.JButton btnPrintFiscalReceipt;
    private javax.swing.JButton btnPrintFiscalReceipt2;
    private javax.swing.JButton btnPrintFiscalReceipt3;
    private javax.swing.JButton btnPrintImage;
    private javax.swing.JButton btnPrintLine;
    private javax.swing.JButton btnPrintNonfiscalReceipt;
    private javax.swing.JButton btnPrintReceiptLogo;
    private javax.swing.JButton btnPrintRefundReceipt;
    private javax.swing.JButton btnPrintSpeedTest;
    private javax.swing.JButton btnReadCashReg;
    private javax.swing.JButton btnReadMaxGraphics;
    private javax.swing.JButton btnReadOperReg;
    private javax.swing.JButton btnReadStatus;
    private javax.swing.JButton btnRelease;
    private javax.swing.JButton btnResetPrinter;
    private javax.swing.JButton btnSetHeaderLines;
    private javax.swing.JButton btnSetTrailerLines;
    private javax.swing.JButton btnXReport;
    private javax.swing.JButton btnZReport;
    private javax.swing.JButton btnZReport1;
    private javax.swing.JComboBox cbLineType;
    private javax.swing.JComboBox cbLogoPosition;
    private javax.swing.JCheckBox chbCashDrawerDeviceEnabled;
    private javax.swing.JCheckBox chbCashDrawerFreezeEvents;
    private javax.swing.JTextField edtCashDrawerBeepDelay;
    private javax.swing.JTextField edtCashDrawerBeepDuration;
    private javax.swing.JTextField edtCashDrawerBeepFrequency;
    private javax.swing.JTextField edtCashDrawerBeepTimeout;
    private javax.swing.JTextField edtCashDrawerDeviceName;
    private javax.swing.JTextField edtCashDrawerTimeout;
    private javax.swing.JTextField edtDayOpened;
    private javax.swing.JTextField edtDeviceName;
    private javax.swing.JTextField edtImageFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JList lbEvents;
    private javax.swing.JLabel lblBarcode;
    private javax.swing.JLabel lblDayOpened;
    private javax.swing.JLabel lblDayOpened1;
    private javax.swing.JLabel lblDayOpened2;
    private javax.swing.JLabel lblDayOpened3;
    private javax.swing.JLabel lblImageFile;
    private javax.swing.JLabel lblImageIndex;
    private javax.swing.JLabel lblLineType;
    private javax.swing.JLabel lblLogoPosition;
    private javax.swing.JLabel lbllineHeight;
    private javax.swing.JPanel pnlCash1;
    private javax.swing.JPanel pnlFptr1;
    private javax.swing.JPanel pnlFptr2;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlReceiptImage;
    private javax.swing.JSpinner seImageIndex;
    private javax.swing.JSpinner seLineHeight;
    private javax.swing.JTabbedPane tabPane1;
    private javax.swing.JTextArea txtReport;
    // End of variables declaration//GEN-END:variables
}
